CREATE TABLE CURSO (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(250) NOT NULL,
  `HORARIO` varchar(5) NOT NULL,
  `DATAINI` date NOT NULL,
  `DATATER` date NOT NULL,
  `NUMVAGAS` int(11) NOT NULL,
  `VALOR` double NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;
